name: Abena Dakwa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88798
title: Abena Dakwa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf4f7'
    - '#3386ca'
    - '#454a5e'
    - '#071b58'
    - '#a76707'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
